import { Sponsor, HeroSlide, Banner, SocialLink, WheelReward, StoreProduct, Giveaway, GiveawayTemplate, SiteSettings, Profile } from '../types';

export const initialSiteSettings: SiteSettings = {
  site_name: 'SHELBYONLINE',
  site_title: 'ShelbyOnline | Premium Sponsor & Kampanya Platformu',
  site_description: 'Doğrulanmış güvenilir sponsor platformları, özel yatırım ve deneme bonusları, günlük çark hediyeleri ve ödüllü topluluk çekilişleri.',
  logo_text: 'SHELBYONLINE',
  logo_tagline: 'PREMIUM SPONSOR & GAMING NETWORK',
  footer_text: 'ShelbyOnline, doğrulanmış eğlence ve sponsorluk ağlarının en güncel bonuslarını sunan bağımsız bir topluluk portalıdır. 18 yaşından küçüklerin katılımı yasaktır.',
  telegram_url: 'https://t.me/shelbyonline',
  telegram_channel_url: 'https://t.me/shelbyonline',
  telegram_chat_url: 'https://t.me/shelbyonline_chat',
  telegram_bot_username: 'ShelbyOnlineBot',
  telegram_bot_token: '8944054737:AAHD_G8mzXVQiYEQnqUDiLa6hSJyRdIyjeY',
  telegram_bot_url: 'https://t.me/ShelbyOnlineBot',
  telegram_login_enabled: true,
  twitter_url: 'https://x.com/shelbyonline',
  instagram_url: 'https://instagram.com/shelbyonline',
  support_email: 'destek@shelbyonline.com',
  maintenance_mode: false,
  registration_enabled: true,
  // Top Announcement Banner
  announcement_enabled: true,
  announcement_text: '🔥 Yeni Sezon Çekilişi Başladı! Telegram ile giriş yapıp +250 Hoş Geldin Coini anında kapın!',
  announcement_link: '/giveaways',
  announcement_badge: 'YENİ ETKİNLİK',
  // Economy & Coins
  welcome_coin_bonus: 250,
  daily_wheel_free_spins: 1,
  // Page Control Toggles (true = aktif, false = pasif/bakımda)
  page_sponsors_enabled: true,
  page_wheel_enabled: true,
  page_giveaways_enabled: true,
  page_leaderboard_enabled: true,
  page_store_enabled: true,
  page_games_enabled: true,
  page_live_enabled: true,
  page_about_enabled: true,
  page_contact_enabled: true,
  // Maintenance text
  maintenance_title: 'Sayfa Geçici Olarak Bakımdadır',
  maintenance_description: 'Yöneticilerimiz bu sayfayı güncelliyor. Lütfen kısa bir süre sonra tekrar ziyaret ediniz.',
};

export const initialProfiles: Profile[] = [
  {
    id: 'user-admin-kajju66',
    username: 'kajju66',
    email: 'kajju66@shelbyonline.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 25000,
    role: 'super_admin',
    active: true,
    telegram_id: '894405473',
    telegram_username: 'kajju66',
    telegram_first_name: 'Kajju',
    telegram_last_name: 'Admin',
    is_telegram_verified: true,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-08-16T12:00:00Z',
  },
  {
    id: 'user-vip-01',
    username: 'BaronKral',
    email: 'baron@shelbyonline.com',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 9850,
    role: 'user',
    active: true,
    telegram_id: '817263541',
    telegram_username: 'baronkral_tg',
    telegram_first_name: 'Baron',
    is_telegram_verified: true,
    created_at: '2026-02-14T11:20:00Z',
    updated_at: '2026-08-14T09:15:00Z',
  },
  {
    id: 'user-vip-02',
    username: 'ZeusSlotMaster',
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 8420,
    role: 'user',
    active: true,
    created_at: '2026-03-01T15:40:00Z',
    updated_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'user-vip-03',
    username: 'VipOyuncu99',
    avatar_url: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 7190,
    role: 'user',
    active: true,
    created_at: '2026-04-12T08:30:00Z',
    updated_at: '2026-08-13T18:20:00Z',
  },
  {
    id: 'user-vip-04',
    username: 'KuzeyRuzgari',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 5400,
    role: 'user',
    active: true,
    created_at: '2026-05-20T14:10:00Z',
    updated_at: '2026-08-12T20:00:00Z',
  },
  {
    id: 'user-vip-05',
    username: 'MatrixCasino',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
    coin_balance: 4850,
    role: 'user',
    active: true,
    created_at: '2026-06-05T19:50:00Z',
    updated_at: '2026-08-10T14:30:00Z',
  },
];

export const initialSponsors: Sponsor[] = [
  {
    id: 'sp-01',
    name: 'NovaBet',
    slug: 'novabet',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="nb" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%2306B6D4"/><stop offset="100%" stop-color="%233B82F6"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%230c102b"/><circle cx="50" cy="50" r="28" fill="url(%23nb)"/><path d="M42 34 L58 50 L42 66 Z" fill="%23ffffff"/><text x="90" y="55" fill="%23ffffff" font-family="system-ui,sans-serif" font-weight="900" font-size="30" letter-spacing="1">NOVA<tspan fill="%2338BDF8">BET</tspan></text><text x="92" y="73" fill="%2394A3B8" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">PREMIUM CASINO &amp; SPORTS</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'NovaBet, uluslararası lisanslı yüksek oranları, anında çekim garantisi ve 7/24 VIP Türkçe canlı destek hizmeti ile sektörün öncü ve en güvenilir sponsor platformudur.',
    short_description: 'Türkiye’nin en hızlı para yatırma ve çekme altyapısına sahip güvenilir premium sponsoru.',
    website_url: 'https://example.com/go/novabet',
    button_text: 'BONUSU AL',
    rating: 4.9,
    featured: true,
    verified: true,
    active: true,
    sort_order: 1,
    clicks_count: 1420,
    bonus_code: 'NOVAVIP',
    min_deposit: '50 ₺',
    withdrawal_speed: '~3 Dk',
    license: 'Curacao 8048/JAZ',
    rtp_rate: '98.4%',
    online_players: 1482,
    badge_text: 'EN POPÜLER SEÇİM',
    accent_color: '#06B6D4',
    payment_methods: ['Papara', 'Payfix', 'Kripto / USDT', 'Fast / Havale', 'Mefete'],
    stats: [
      { id: 'stat-01', label: 'İlk Yatırım', value: '%150 Bonus', sort_order: 1 },
      { id: 'stat-02', label: 'Deneme', value: '500 TL Free', sort_order: 2 },
      { id: 'stat-03', label: 'Kayıp İade', value: '%25 Anlık', sort_order: 3 },
    ],
    features: [
      { id: 'feat-01', text: '5 Dakikada Anında Limitsiz Çekim', sort_order: 1 },
      { id: 'feat-02', text: 'Çevrimsiz %20 Kripto & Papara Bonusu', sort_order: 2 },
      { id: 'feat-03', text: 'Özel VIP Turnuvalar & Aylık Çekilişler', sort_order: 3 },
      { id: 'feat-04', text: '7/24 Kesintisiz Canlı Destek & WhatsApp', sort_order: 4 },
    ],
  },
  {
    id: 'sp-02',
    name: 'RoyalPlay',
    slug: 'royalplay',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="rp" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23F59E0B"/><stop offset="50%" stop-color="%23FCD34D"/><stop offset="100%" stop-color="%23D97706"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%231a0f05"/><path d="M30 62 L30 46 L38 54 L50 36 L62 54 L70 46 L70 62 Z" fill="url(%23rp)"/><circle cx="50" cy="34" r="4" fill="%23EF4444"/><text x="88" y="55" fill="url(%23rp)" font-family="system-ui,sans-serif" font-weight="900" font-size="30" letter-spacing="1">ROYAL<tspan fill="%23FFFFFF">PLAY</tspan></text><text x="90" y="73" fill="%23FBBF24" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">VIP PALACE &amp; SLOTS</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'RoyalPlay, zengin canlı casino masaları, binlerce popüler slot oyunu ve özel sadakat programıyla oyuncularına saray standartlarında bir deneyim vadediyor.',
    short_description: 'Saray standartlarında VIP casino ve yüksek çarpanlı slot oyunları.',
    website_url: 'https://example.com/go/royalplay',
    button_text: 'BONUSU AL',
    rating: 4.8,
    featured: true,
    verified: true,
    active: true,
    sort_order: 2,
    clicks_count: 1180,
    bonus_code: 'ROYAL250',
    min_deposit: '100 ₺',
    withdrawal_speed: '~2 Dk',
    license: 'Malta MGA/B2C/394/2017',
    rtp_rate: '98.7%',
    online_players: 1180,
    badge_text: 'VIP SARAYI',
    accent_color: '#F59E0B',
    payment_methods: ['Papara', 'Payfix', 'Kripto / USDT', 'Banka Havalesi', 'Fast'],
    stats: [
      { id: 'stat-04', label: 'Hoş Geldin', value: '%200 + 250 FS', sort_order: 1 },
      { id: 'stat-05', label: 'Deneme', value: '350 TL Nakit', sort_order: 2 },
      { id: 'stat-06', label: 'Discount', value: '%30 Günlük', sort_order: 3 },
    ],
    features: [
      { id: 'feat-05', text: 'Özel Pragmatic Play Masaları ve Turnuvalar', sort_order: 1 },
      { id: 'feat-06', text: 'Yatırım Şartsız 250 Freespin Deneme', sort_order: 2 },
      { id: 'feat-07', text: 'Tüm Bankalara 7/24 Fast Transfer', sort_order: 3 },
      { id: 'feat-08', text: 'Haftalık Kayıplara Ekstra %10 Cashback', sort_order: 4 },
    ],
  },
  {
    id: 'sp-03',
    name: 'WinZone',
    slug: 'winzone',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="wz" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%2310B981"/><stop offset="100%" stop-color="%2306B6D4"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%23061a14"/><path d="M52 28 L36 54 L48 54 L44 72 L64 46 L50 46 Z" fill="url(%23wz)"/><text x="84" y="55" fill="%23FFFFFF" font-family="system-ui,sans-serif" font-weight="900" font-size="32" font-style="italic" letter-spacing="1">WIN<tspan fill="%2310B981">ZONE</tspan></text><text x="86" y="73" fill="%236EE7B7" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">HIGH ODDS BETTING</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'WinZone, spor bahislerinde en yüksek oranları ve e-spor arenalarını tek çatı altında toplayan global ödüllü bahis ve casino markasıdır.',
    short_description: 'En yüksek oranlar, tek maça kombine ve zengin canlı bahis bülteni.',
    website_url: 'https://example.com/go/winzone',
    button_text: 'BONUSU AL',
    rating: 4.7,
    featured: true,
    verified: true,
    active: true,
    sort_order: 3,
    clicks_count: 940,
    bonus_code: 'WIN500',
    min_deposit: '50 ₺',
    withdrawal_speed: '~5 Dk',
    license: 'Curacao 1668/JAZ',
    rtp_rate: '97.9%',
    online_players: 940,
    badge_text: 'EN YÜKSEK ORAN',
    accent_color: '#10B981',
    payment_methods: ['Papara', 'Payfix', 'Kripto / USDT', 'Havale / EFT', 'QR'],
    stats: [
      { id: 'stat-07', label: 'İlk Yatırım', value: '%100 Spor', sort_order: 1 },
      { id: 'stat-08', label: 'Deneme', value: '400 TL Freebet', sort_order: 2 },
      { id: 'stat-09', label: 'Kombine', value: '%50 Ekstra', sort_order: 3 },
    ],
    features: [
      { id: 'feat-09', text: 'Yüksek Oranlı Canlı Maç Yayınları (WinTV)', sort_order: 1 },
      { id: 'feat-10', text: 'Bahis Bozdur (Cashout) & Düzenle Özelliği', sort_order: 2 },
      { id: 'feat-11', text: 'Çevrimsiz Her Yatırıma %15 Nakit Hediye', sort_order: 3 },
      { id: 'feat-12', text: 'Kripto ile Güvenli ve Anonim Çekimler', sort_order: 4 },
    ],
  },
  {
    id: 'sp-04',
    name: 'LuckyClub',
    slug: 'luckyclub',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="lc" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%2384CC16"/><stop offset="100%" stop-color="%2310B981"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%230a1c12"/><circle cx="50" cy="50" r="26" fill="url(%23lc)"/><text x="50" y="58" fill="%23FFFFFF" font-family="system-ui,sans-serif" font-weight="900" font-size="22" text-anchor="middle">777</text><text x="90" y="55" fill="%23FFFFFF" font-family="system-ui,sans-serif" font-weight="900" font-size="28" letter-spacing="1">LUCKY<tspan fill="%2384CC16">CLUB</tspan></text><text x="92" y="73" fill="%23A3E635" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">JACKPOT &amp; FREESPINS</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'LuckyClub, rengarenk slot havuzları, devasa jackpotlar ve her gün yenilenen sürpriz çark ödülleriyle şansını katlamak isteyenlerin bir numaralı adresi.',
    short_description: 'Büyük jackpot havuzları ve günlük sınırsız freespin yağmuru.',
    website_url: 'https://example.com/go/luckyclub',
    button_text: 'BONUSU AL',
    rating: 4.8,
    featured: true,
    verified: true,
    active: true,
    sort_order: 4,
    clicks_count: 890,
    bonus_code: 'LUCKY777',
    min_deposit: '50 ₺',
    withdrawal_speed: '~4 Dk',
    license: 'Anjouan eGaming ALSI-02240',
    rtp_rate: '98.2%',
    online_players: 890,
    badge_text: 'SLOT CENNETİ',
    accent_color: '#84CC16',
    payment_methods: ['Papara', 'Payfix', 'USDT', 'Kredi Kartı', 'Fast'],
    stats: [
      { id: 'stat-10', label: 'Slot Bonusu', value: '%300 Jackpot', sort_order: 1 },
      { id: 'stat-11', label: 'Deneme', value: '300 Freespin', sort_order: 2 },
      { id: 'stat-12', label: 'Nakit İade', value: '%20 Net', sort_order: 3 },
    ],
    features: [
      { id: 'feat-13', text: 'Milyonluk Progressive Jackpot Havuzu', sort_order: 1 },
      { id: 'feat-14', text: 'Günün Her Saati 100.000 TL Tek Çekim', sort_order: 2 },
      { id: 'feat-15', text: 'Hafta Sonu Özel %50 Yatırım Fırsatı', sort_order: 3 },
      { id: 'feat-16', text: 'Özel Mobil iOS ve Android Uygulamaları', sort_order: 4 },
    ],
  },
  {
    id: 'sp-05',
    name: 'GrandVegas',
    slug: 'grandvegas',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="gv" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23EC4899"/><stop offset="100%" stop-color="%238B5CF6"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%231a0921"/><polygon points="50,28 56,42 70,42 58,52 62,66 50,56 38,66 42,52 30,42 44,42" fill="%23F59E0B"/><text x="86" y="55" fill="url(%23gv)" font-family="system-ui,sans-serif" font-weight="900" font-size="26" letter-spacing="1">GRAND<tspan fill="%23FCD34D">VEGAS</tspan></text><text x="88" y="73" fill="%23F472B6" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">AUTHENTIC LIVE DEALERS</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'Las Vegas ışıltısını evinize getiren GrandVegas, Türkçe krupiyeli masaları ve sınırsız masa limitleriyle gerçek kumarhane atmosferi sunar.',
    short_description: 'Otantik Vegas atmosferi ve Türkçe konuşan canlı krupiyeler.',
    website_url: 'https://example.com/go/grandvegas',
    button_text: 'BONUSU AL',
    rating: 4.6,
    featured: false,
    verified: true,
    active: true,
    sort_order: 5,
    clicks_count: 670,
    bonus_code: 'VEGAS100',
    min_deposit: '100 ₺',
    withdrawal_speed: '~3 Dk',
    license: 'Curacao 5536/JAZ',
    rtp_rate: '98.1%',
    online_players: 670,
    badge_text: 'CANLI KRUPİYELER',
    accent_color: '#EC4899',
    payment_methods: ['Papara', 'Payfix', 'Kripto / USDT', 'Havale / Fast'],
    stats: [
      { id: 'stat-13', label: 'Canlı Casino', value: '%100 VIP Masalar', sort_order: 1 },
      { id: 'stat-14', label: 'Deneme', value: '250 TL Rulet', sort_order: 2 },
      { id: 'stat-15', label: 'Haftalık', value: '10.000 TL Cashback', sort_order: 3 },
    ],
    features: [
      { id: 'feat-17', text: 'Özel Türkçe Blackjack ve Rulet Masaları', sort_order: 1 },
      { id: 'feat-18', text: 'Yüksek Limitli VIP Salonlar & Özel Danışman', sort_order: 2 },
      { id: 'feat-19', text: 'Anında Kripto Para Yatırma ve Çekme', sort_order: 3 },
    ],
  },
  {
    id: 'sp-06',
    name: 'RexCasino',
    slug: 'rexcasino',
    logo_url: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100" width="300" height="100"><defs><linearGradient id="rc" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23EF4444"/><stop offset="100%" stop-color="%23F97316"/></linearGradient></defs><rect width="300" height="100" rx="16" fill="%231f0808"/><path d="M38 64 L50 32 L62 64 L50 56 Z" fill="url(%23rc)"/><text x="84" y="55" fill="%23FFFFFF" font-family="system-ui,sans-serif" font-weight="900" font-size="30" letter-spacing="1">REX<tspan fill="%23EF4444">CASINO</tspan></text><text x="86" y="73" fill="%23FCA5A5" font-family="system-ui,sans-serif" font-weight="700" font-size="10" letter-spacing="3">CRASH &amp; AVIATOR ARENA</text></svg>',
    banner_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&h=400&q=80',
    description: 'RexCasino, yeni nesil Crash oyunları (Aviator, Spaceman, Mines) ve modern arayüzüyle hızlı kazanç peşinde olanların favorisi.',
    short_description: 'Yeni nesil Crash oyunları, Aviator ve ultra hızlı çekimler.',
    website_url: 'https://example.com/go/rexcasino',
    button_text: 'BONUSU AL',
    rating: 4.7,
    featured: false,
    verified: true,
    active: true,
    sort_order: 6,
    clicks_count: 530,
    bonus_code: 'REXCRASH',
    min_deposit: '50 ₺',
    withdrawal_speed: '~1 Dk',
    license: 'Curacao 8048/JAZ',
    rtp_rate: '99.1%',
    online_players: 530,
    badge_text: 'AVIATOR & CRASH',
    accent_color: '#EF4444',
    payment_methods: ['Papara', 'Payfix', 'Kripto / USDT', 'Fast / Havale'],
    stats: [
      { id: 'stat-16', label: 'Crash Özel', value: '%200 Çevrimsiz', sort_order: 1 },
      { id: 'stat-17', label: 'Deneme', value: '500 TL Aviator', sort_order: 2 },
      { id: 'stat-18', label: 'Kayıp İade', value: '%20 Her Gün', sort_order: 3 },
    ],
    features: [
      { id: 'feat-20', text: 'Aviator, Zeppelin ve Mines için Özel Bonuslar', sort_order: 1 },
      { id: 'feat-21', text: 'Otomatik Çekim Sistemi (1 Dakika Onay)', sort_order: 2 },
      { id: 'feat-22', text: 'Telegram Topluluğuna Özel Kod Dağıtımları', sort_order: 3 },
    ],
  },
];

export const initialHeroSlides: HeroSlide[] = [
  {
    id: 'slide-01',
    title: '🏆 250.000 TL BÜYÜK YAZ TURNUVASI BAŞLADI!',
    subtitle: 'NovaBet & WinZone ortaklığında haftalık nakit ödüllü dev çekilişte yerinizi hemen ayırtın.',
    desktop_image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1350&h=380&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&h=300&q=80',
    button_text: 'DEV TURNUVAYA KATIL',
    target_url: '/giveaways',
    sort_order: 1,
    active: true,
  },
  {
    id: 'slide-02',
    title: '💎 GÜNLÜK VIP ÇARK ÇEVİR & COIN KAZAN',
    subtitle: 'Her gün platforma giriş yap, şans çarkını çevir ve mağazada harcayabileceğin binlerce coin topla.',
    desktop_image: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=1350&h=380&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=600&h=300&q=80',
    button_text: 'ŞANS ÇARKINI ÇEVİR',
    target_url: '/wheel',
    sort_order: 2,
    active: true,
  },
  {
    id: 'slide-03',
    title: '🚀 %300 HOŞ GELDİN + 500 FREESPIN FIRSATI',
    subtitle: 'Doğrulanmış güvenilir sponsorlarımızda anında çevrimsiz nakit iade ve limitsiz çekim güvencesi.',
    desktop_image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1350&h=380&q=80',
    mobile_image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&h=300&q=80',
    button_text: 'SPONSORLARI İNCELE',
    target_url: '/sponsors',
    sort_order: 3,
    active: true,
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-01',
    name: 'NovaBet Sol Dikey Banner',
    image_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=160&h=600&q=80',
    target_url: '/site/novabet',
    position: 'left',
    active: true,
    sort_order: 1,
    clicks_count: 320,
  },
  {
    id: 'ban-02',
    name: 'RoyalPlay Sağ Dikey Banner',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=160&h=600&q=80',
    target_url: '/site/royalplay',
    position: 'right',
    active: true,
    sort_order: 1,
    clicks_count: 290,
  },
];

export const initialSocialLinks: SocialLink[] = [
  {
    id: 'soc-01',
    platform: 'telegram_chat',
    title: 'Telegram VIP Sohbet',
    subtitle: '5.800+ Aktif Üye',
    url: 'https://t.me/sponsorhub_chat',
    icon: 'MessageSquare',
    active: true,
    sort_order: 1,
  },
  {
    id: 'soc-02',
    platform: 'telegram_channel',
    title: 'Telegram Resmi Duyuru',
    subtitle: 'Anlık Kodlar & Promosyonlar',
    url: 'https://t.me/sponsorhub_duyuru',
    icon: 'Send',
    active: true,
    sort_order: 2,
  },
  {
    id: 'soc-03',
    platform: 'twitter',
    title: 'Resmi X (Twitter)',
    subtitle: 'Ödüllü Sosyal Etkinlikler',
    url: 'https://x.com/sponsorhub',
    icon: 'Twitter',
    active: true,
    sort_order: 3,
  },
];

export const initialWheelRewards: WheelReward[] = [
  { id: 'wr-01', title: '25 Coin', reward_type: 'coin', reward_value: 25, color: '#7C3AED', probability: 28.0, active: true, sort_order: 1 },
  { id: 'wr-02', title: '50 Coin', reward_type: 'coin', reward_value: 50, color: '#8B5CF6', probability: 24.0, active: true, sort_order: 2 },
  { id: 'wr-03', title: '100 Coin', reward_type: 'coin', reward_value: 100, color: '#A855F7', probability: 16.0, active: true, sort_order: 3 },
  { id: 'wr-04', title: '250 Coin', reward_type: 'coin', reward_value: 250, color: '#EAB308', probability: 8.0, active: true, sort_order: 4 },
  { id: 'wr-05', title: '500 VIP Coin', reward_type: 'coin', reward_value: 500, color: '#F59E0B', probability: 4.0, active: true, sort_order: 5 },
  { id: 'wr-06', title: 'Tekrar Dene', reward_type: 'retry', reward_value: 0, color: '#475569', probability: 10.0, active: true, sort_order: 6 },
  { id: 'wr-07', title: 'Özel Promosyon', reward_type: 'bonus', reward_value: 75, color: '#EC4899', probability: 10.0, active: true, sort_order: 7 },
];

export const initialGiveaways: Giveaway[] = [
  {
    id: 'giv-01',
    title: 'iPhone 16 Pro Max Büyük Yaz Çekilişi',
    description: 'ShelbyOnline topluluk üyelerine özel haftalık dev çekiliş! Ücretsiz katılın, son teknoloji iPhone 16 Pro Max kazanın.',
    image_url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&h=450&q=80',
    prize_details: '1x Apple iPhone 16 Pro Max 256GB Titanyum',
    start_at: new Date().toISOString(),
    end_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    active: true,
    winner_count: 1,
    entries_count: 342,
  },
  {
    id: 'giv-02',
    title: '50.000 TL Topluluk Nakit Dağıtımı',
    description: '10 şanslı üyemize kişi başı 5.000 TL anında havale/Papara nakit ödülü! Tek tıkla çekilişe adını yazdır.',
    image_url: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=800&h=450&q=80',
    prize_details: '10x 5.000 TL Nakit Havale Ödülü',
    start_at: new Date().toISOString(),
    end_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    active: true,
    winner_count: 10,
    entries_count: 819,
  },
  {
    id: 'giv-03',
    title: 'PlayStation 5 Pro + 2 Kol Mega Paket',
    description: 'Yeni nesil Sony PlayStation 5 Pro konsol paketi ile oyun keyfini zirveye taşıyın.',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&h=450&q=80',
    prize_details: '1x Sony PS5 Pro Konsol + 2 DualSense Kol',
    start_at: new Date().toISOString(),
    end_at: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    active: true,
    winner_count: 1,
    entries_count: 512,
  },
];

export const initialStoreProducts: StoreProduct[] = [
  {
    id: 'prod-01',
    name: '100 TL Steam Cüzdan Kodu',
    description: 'Tüm Steam mağazasında geçerli anında teslim dijital cüzdan pin kodu.',
    image_url: 'https://images.unsplash.com/photo-1612287233261-267039757657?auto=format&fit=crop&w=500&h=350&q=80',
    coin_price: 350,
    stock: 45,
    category: 'digital',
    active: true,
    sort_order: 1,
  },
  {
    id: 'prod-02',
    name: '250 TL Trendyol Alışveriş Çeki',
    description: 'Giyim, teknoloji ve süpermarket dahil tüm kategorilerde geçerli hediye kuponu.',
    image_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=500&h=350&q=80',
    coin_price: 750,
    stock: 28,
    category: 'gift_card',
    active: true,
    sort_order: 2,
  },
  {
    id: 'prod-03',
    name: 'PlayStation Network 250 TL Kodu',
    description: 'PS4 ve PS5 mağaza harcamalarında geçerli dijital bakiye kodu.',
    image_url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=500&h=350&q=80',
    coin_price: 800,
    stock: 19,
    category: 'digital',
    active: true,
    sort_order: 3,
  },
  {
    id: 'prod-04',
    name: 'VIP Rozeti & 2x Günlük Çark (30 Gün)',
    description: 'Toplulukta havalı VIP çerçevesi ve her gün 1 yerine 2 kez şans çarkı çevirme ayrıcalığı.',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=500&h=350&q=80',
    coin_price: 500,
    stock: 999,
    category: 'membership',
    active: true,
    sort_order: 4,
  },
];

export const initialGiveawayTemplates: GiveawayTemplate[] = [
  {
    id: 'tpl-ps5',
    name: '🎮 PS5 Paketi',
    title: 'Haftalık PlayStation 5 & Nakit Çekilişi',
    prize_details: '1x Sony PS5 Slim + 50.000 TL Nakit Ödül',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Topluluk üyelerimize özel dev çekiliş. Tek tıkla hemen katıl.',
    duration_days: 7,
    badge_color: 'violet',
  },
  {
    id: 'tpl-iphone',
    name: '📱 iPhone 16 Pro',
    title: 'iPhone 16 Pro Max Büyük Yaz Çekilişi',
    prize_details: '1x Apple iPhone 16 Pro Max 256GB Titanyum',
    image_url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'En son model iPhone 16 Pro Max hediyesi. Şansını kaçırma.',
    duration_days: 7,
    badge_color: 'rose',
  },
  {
    id: 'tpl-cash',
    name: '💰 100.000 TL Nakit',
    title: '100.000 TL Topluluk Nakit Dağıtımı',
    prize_details: '100.000 TL Nakit Ödül (Banka Havalesi / Papara / Kripto)',
    image_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Her hafta dev nakit ödüller topluluğumuza dağıtılıyor.',
    duration_days: 5,
    badge_color: 'amber',
  },
  {
    id: 'tpl-crypto',
    name: '💎 25.000 TL USDT',
    title: '25.000 TL Değerinde Kripto & USDT Ödülü',
    prize_details: '1.000 USDT (Tether) Anında Kripto Cüzdanınıza Teslim',
    image_url: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Kripto dünyasının en popüler çekilişi. Doğrulanmış cüzdanlara anında transfer.',
    duration_days: 3,
    badge_color: 'emerald',
  },
  {
    id: 'tpl-bonus',
    name: '🎰 1.000 Freespin + VIP',
    title: 'Mega Slot Paketi & VIP Nakit Çevrim Bonusu',
    prize_details: '1.000 Gates of Olympus Freespin + 10.000 TL Nakit Bonus',
    image_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=800&h=450&q=80',
    description: 'Sponsor sitelerimizde geçerli dev freespin ve bonus dağıtımı.',
    duration_days: 3,
    badge_color: 'cyan',
  },
];

